# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Z
tagline:             'Be the change you want to see in the world.'
description:         'Be the change you want to see in the world.'
url:                 http://shawlyn-chen.com
baseurl:             'http://shawlyn-chen.com'
paginate:            5

# About/contact
author:
  name:              Shawlyn Chen
  url:               http://shawlyn-chen.com
  email:             

# Custom vars
version:             1.0.0
