# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Z
tagline:             'Be the change you want to see in the world.'
description:         'Be the change you want to see in the world.'
url:                 http://xiongzh.com
baseurl:             'http://xiongzh.com'
paginate:            5

# About/contact
author:
  name:              Zhen XIONG
  url:               http://xiongzh.com
  email:             837075787@qq.com

# Custom vars
version:             1.0.0
